/* The app is split across a dozen plain scripts with no module system, so the
   only thing holding it together is the <script> list in index.html. Two ways
   that goes wrong quietly:

     - a new file is written but never added to the page, so it works in the
       tests (which read the same list) but not in the browser, or the reverse
     - two files declare the same top-level name, which in a browser throws
       "Identifier has already been declared" and takes the whole page down
       before anything renders

   Neither is caught by a test of behaviour, because behaviour never gets to
   run. So they're caught here instead. */

const fs = require("fs");
const path = require("path");

module.exports = function (suite) {
  const harness = require("./harness");
  const listed = harness.scriptFiles();

  suite.section("the page loads every script there is");
  /* sw.js is the one script the page must NOT load: a service worker runs
     outside the document and is registered by app.js, not tagged into the head.
     Everything else on disk has to be in the list. */
  const NOT_PAGE_SCRIPTS = ["sw.js"];
  const onDisk = fs.readdirSync(harness.ROOT).filter(f => f.endsWith(".js")).sort();
  const orphaned = onDisk.filter(f => !listed.includes(f) && !NOT_PAGE_SCRIPTS.includes(f));
  suite.is("no script is left out of index.html", orphaned, []);
  const phantom = listed.filter(f => !fs.existsSync(path.join(harness.ROOT, f)));
  suite.is("and none is listed that doesn't exist", phantom, []);

  suite.section("the load order");
  suite.is("reference data comes first", listed[0], "srd-data.js");
  const refDataFiles = listed.filter(f => /^srd-/.test(f));
  const afterRefData = listed[refDataFiles.length];
  suite.ok("every srd-*.js file loads as one contiguous block up front",
    listed.slice(0, refDataFiles.length).every(f => /^srd-/.test(f)),
    "found a non-reference-data file inside the srd-*.js block: " + listed.slice(0, refDataFiles.length).join(", "));
  suite.is("then the character, right after the reference data block", afterRefData, "character-data.js");
  suite.is("and app.js starts everything last", listed[listed.length - 1], "app.js");

  suite.section("no two files declare the same name");
  /* Only top-level declarations matter -- anything indented is inside a
     function and has its own scope. */
  const declarations = {};
  listed.forEach(file => {
    const source = harness.readFile(file);
    [...source.matchAll(/^(?:function|let|const|var)\s+([A-Za-z_$][\w$]*)/gm)]
      .forEach(match => {
        const name = match[1];
        (declarations[name] = declarations[name] || []).push(file);
      });
  });

  const clashes = Object.keys(declarations)
    .filter(name => new Set(declarations[name]).size > 1)
    .map(name => name + " (" + [...new Set(declarations[name])].join(", ") + ")");
  suite.is("every top-level name is declared once", clashes, []);

  /* The form primitives only help if they're used. A hand-written field is a
     field whose value nobody remembered to escape, whose margin doesn't match
     its neighbour, and which won't pick up the next change to what a field
     looks like. ui.js is where the markup is allowed to exist. */
  suite.section("form markup is built, not typed");
  ["field", "toggle-line"].forEach(className => {
    const offenders = listed
      .filter(file => file !== "ui.js")
      .filter(file => harness.readFile(file).includes('class="' + className + '"'));
    suite.is("no file hand-writes a " + className, offenders, []);
  });

  /* A <button> inside a <button> is invalid HTML, and the browsers disagree
     about it: Chromium keeps the nesting, every spec-compliant parser closes
     the outer one. That shipped once -- the weapon property picker put a
     mini-checkbox button inside a row button, which rendered correctly in
     Chromium and collapsed into three stacked siblings in Firefox, with the
     label outside the tap target and the checkbox wired to nothing.

     Nothing else could have caught it. The DOM stub never parses markup, so
     behaviour tests stay green; the source looks perfectly reasonable; and it
     only breaks on an engine the review wasn't run against. So it's caught
     here, by reading the markup as text -- no parser, no dependency, just
     "did a tag open again before the last one closed".

     Comments are stripped first, because half the explanation of this bug is
     written in prose containing the very tags it's looking for. */
  /* A file the page loads but the worker doesn't cache works perfectly right up
     until the phone loses signal, and then fails somewhere nobody can reproduce.
     The list is generated by tools/build-sw.js from this same index.html; this
     is what fails when someone adds a script and forgets to re-run it. */
  suite.section("the service worker caches everything the page loads");
  const swAssets = (harness.readFile("sw.js").match(/const ASSETS = \[([\s\S]*?)\]/) || [])[1] || "";
  const cached = [...swAssets.matchAll(/"([^"]+)"/g)].map(m => m[1]);
  suite.is("every page script is cached", listed.filter(f => !cached.includes(f)), []);
  ["index.html", "style.css", "manifest.json"].forEach(asset => {
    suite.ok(asset + " is cached", cached.includes(asset), "missing from the worker's list");
  });
  suite.is("and nothing is cached that isn't on disk",
    cached.filter(a => a !== "./" && !fs.existsSync(path.join(harness.ROOT, a))), []);

  suite.section("no interactive element nests inside another");

  const stripComments = text => text
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");

  ["button", "a", "form"].forEach(tag => {
    const offenders = [];
    listed.forEach(file => {
      const text = stripComments(harness.readFile(file));
      const tokens = text.match(new RegExp("<\\/?" + tag + "(?=[\\s>])", "g")) || [];
      let depth = 0;
      tokens.forEach(token => {
        if (token[1] === "/") depth = Math.max(0, depth - 1);
        else if (++depth > 1) { if (!offenders.includes(file)) offenders.push(file); }
      });
    });
    suite.is("no file nests a <" + tag + "> inside another <" + tag + ">", offenders, []);
  });

  suite.section("the primitives escape what they're given");
  const app = harness.loadApp();
  const HOSTILE = '<img src=x onerror=alert(1)>';
  [["textFieldHtml", app.textFieldHtml("i", HOSTILE, HOSTILE, { placeholder: HOSTILE, hint: HOSTILE })],
   ["numberFieldHtml", app.numberFieldHtml("i", HOSTILE, HOSTILE, { placeholder: HOSTILE })],
   ["textAreaFieldHtml", app.textAreaFieldHtml("i", HOSTILE, HOSTILE, { placeholder: HOSTILE })],
   ["toggleLineHtml", app.toggleLineHtml("i", HOSTILE, true, { note: HOSTILE, hint: HOSTILE })],
   ["fieldLabelHtml", app.fieldLabelHtml(HOSTILE)]]
    .forEach(([name, html]) => {
      suite.ok(name, !html.includes("<img src=x"), "raw markup survived");
    });

  suite.section("nothing grew back into a monolith");
  const sizes = listed.map(file => ({ file, lines: harness.readFile(file).split("\n").length }));
  const worst = sizes.reduce((a, b) => (b.lines > a.lines ? b : a));
  suite.ok("the largest file is under 1,500 lines",
    worst.lines < 1500, worst.file + " is " + worst.lines);
  suite.ok("app.js is a boot file, not a codebase",
    sizes.find(s => s.file === "app.js").lines < 120,
    "app.js is " + sizes.find(s => s.file === "app.js").lines + " lines");
};
